- pax/config/XENON1T.ini
- pax/core.py
- pax/plugins/io/ROOTClass.py
This includes a few small fixes for processing XENON1T data:
* "Fix" (in a very dirty way) a race condition in the ROOT output during multiprocessing, where several threads tried to write and/or compile the event class cpp file at the same time;
* Turn off 3d posrec for now, it's nonsense in gas (LCE map for liquid) anyway, and it slows the processing  by a factor 5-10.
* Don't crash if pulses are completely outside the event . This indicates there is still (probably) an off-by-one error in the event builder... I though this protection was enabled before, but it probably got lost.
> Small fixes for XENON1T processing

- pax/simulation.py
A small fix for a bug I encountered while playing around with FaX (if indeed the simulation module logger is to be used).
> Fixed a case of the FaX physics backend trying to use a non-existing logger.

- pax/config/XENON100.ini
- pax/config/XENON1T.ini
- pax/simulation.py
Photons are emitted uniformly within a configurable time interval instead of following excimer decay time distributions, resulting in an LED-like light source.
This addition is motivated by making PMT afterpulse measurement simulations possible with FaX. If needed, a better LED simulation could be achieved in the future by dedicated measurements of the LED hit time distribution ([similar to Jelle's hitfinder calibration note][1]).
[1]: https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon100:analysis:led_pax#when_does_the_led_fire
> Implemented a new 'LED' recoil type.

- pax/config/_base.ini
This sets the default trigger settings to the ones we used over the last few weeks: trigger always above 50 pulses, with 50 us left and right of each trigger. This will capture high-energy events up to 100us apart (since both the S1 and S2 trigger).
Last week we set these settings manually or via a custom config file. When the rate has gone down and the lifetime has gone up, we should of course put wider left and right extensions.
> Saner trigger defaults

- pax/config/XENON1T.ini
These are some small changes to the cable map json in XENON1T.ini:
* Separate connector and channel fields. So no more strings '8.04', but separate integer fields `connector=8` and `channel=4`.
* PMT serial numbers now stored as ints, not floats 
* Add amplifier information. I thought I already did this... but apparently I forgot to commit it.
I also correct an error I introduced in #361: the placeholder gain for the diagnostic PMTs should be 2e6 rather than 4.8e6, since these are 1-inch XENON100 PMTs running at similar voltages as in XENON100.
> Fixes/additions to PMT map in ini

- pax/datastructure.py
- pax/plugins/io/ROOTClass.py
This fixes an error reported by Patrick and Alfio where, if the first event we process does not contain a peak, the resulting root class is not created correctly, and processing may eventually crash. 
The C++ class creation code requires an instance of a datastructure class (like Peak) rather than just the class itself. The class code does not hardcode the length of fixed-length array fields (such as peak.area_per_channel), so we can use pax for multiple TPCs by just changing the configuration.
When the first event we process has no peak (or another datastructure, such as Interaction or ConfidenceTuple), pax attempts to create an empty peak (or Interaction or ConfidenceTuple). This fix sets the array lengths of that empty peak correctly based on the configuration.
This is no long-term …
> Fix for root class creation if no peaks in first event

- pax/plugins/DeleteLowLevelInfo.py
This is a minor change to make DeleteLowLevelInfo, the plugin which removes low-level info from the datastructure, configurable. By setting `delete_hits_and_pulses = False`, for example, you can output hits and pulses for all peaks, but still not output the event sum waveforms (which would probably crash the  output, since we don't support variable-length numpy arrays).
> Configurable DeleteLowLevelInfo

- pax/PatternFitter.py
We currently get the message
/home/jelle/anaconda3/envs/pax/lib/python3.4/site-packages/numpy/lib/nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered
warnings.warn("All-NaN axis encountered", RuntimeWarning)
every ~50 events so. This happens when a list in the confidence contour calculation contains only NaN values. 
@pelssers maybe you'd like to have a look at these edge cases later. For now I just avoided the warning by leaving the confidencetuple's values at nan (which would probably have been the result anyway).
> Avoid numpy runtime warnings from failed confidence contours

- bin/event-builder
- pax/configuration.py
- pax/core.py
- pax/plugins/io/Plotting.py
This allows us to specify overrides for the trigger configuration in the run doc. For example, have a look at the alphas_stable runmode, which has this:
"trigger_config_override": {
"Trigger|DecideTriggers": {
"trigger_probability": {
"0": { "2": 0},
"1": {"50": 0.01, "100": 1},
"2": {"50": 0.01}
}
},
"Trigger|ClassifySignals": {
"s1_max_rms": 12
}
},
which prescales normal signals by 1%, but lets narrow, large-area S1s pass. I tested this with a small run, it seems to work.
The `|` is necessary because `.` in field names has a special meaning in Mongo. It is translated to `.` when the config is loaded.
Also includes a minor plotting fix, and adresses #359 by writing a trigger exception to the log and marking the trigger status of the run as 'error' (as opposed to leaving it …
> Trigger config from runmodes

- bin/event-builder
If new exception we didn't expect, then stop acquisition, report on website to acknowledge, and raise.
We should also have a slow control alarm using their system.
> Error handling and communication with readers.

- bin/event-builder
This ensures the eventbuilder log is copied out to the data directory even in case of a crash, see #359. I have not tested it.
> Copy out log file even in case of a crash

- pax/config/XENON1T.ini
This configures pax and the event builder to read out the acquisition monitor channels (see #204). The current acquisition monitor map is:
* Module 167, channel 0 = "PMT" 254: analog sum waveform
* Module 167, channel 1 = "PMT" 255: busy signals. The busy spikes once or twice in very rapid succession (few samples) depending if it turns on or off.
* Module 167, channel 2 = "PMT" 256: high-energy veto. 
Each of these acquisition monitor channel gets its own separate 'detector' in the pax configuration. They also have a gain attached so the sum waveforms actually appear in the event display, although this is now just something I chose to make the plots look reasonable. For the analog sum there probably is a correct value -- does anyone know what it is?
After merging this pull request, the …
> Read out acquisittion monitor channels

- pax/MongoDB_ClientMaker.py
- pax/config/XENON1T.ini
- pax/config/eventbuilder.ini
- pax/config/reduce_raw_data.ini
- pax/plugins/io/MongoDB.py
- pax/trigger_plugins/DeadTimeTally.py
This upgrades the eventbuilder to deal with the new MongoDB setup (split hosts), and changes the raw data format to one that is 2x faster to create for the trigger (which means our top speed is much improved). The format is now gzip-compressed pickles rather than gzip-compressed bsons. 
Until this is merged and the pax on midway is updated, we won't be able to process the data we're taking. We will be able to reprocess old data after the merge, I've updated the run docs for old runs (<1933) to tell pax to expect the old output format.
> Eventbuilder upgrade & raw data format change

- pax/config/reduce_raw_data.ini
- pax/trigger.py
It would make the trigger monitor frontend much easier if we implement this change. The idea is to save trigger data as arrays, which can be queried and manipulated in the aggregation pipeline and not as compressed ndarrays, which generally have to be fully unpacked before they are useful.
A side effect is that the format will change for trigger monitor data stored offline. We will have to put a small update to hax to test what the format is so it can read properly.
> Reformat trigger data to use list

- .travis.yml
- bin/event-builder
- pax/FolderIO.py
- pax/config/_base.ini
- pax/core.py
- pax/data_model.py
- pax/datastructure.py
- pax/plugins/ZLE.py
- pax/plugins/io/MongoDB.py
- pax/plugins/io/XED.py
- pax/plugins/signal_processing/CheckPulses.py
This slightly improves the speed of the event builder by:
* Dropping the continuous type checking on the pulse class (StrictModel->Model). A few other places in the code had to be updated to provide nice vanilla python types (and not numpy types that would break BSON encoding).
* Add a `do_it_fast=True` option for Model.__init__ that bypasses some of the extra features we use for conveniently serializing entire events. This is only activated when initializing pulses in the event builder.
* Increase the default pymongo batch size, avoiding extra round trips to the database.
This also includes a command line option for starting event building in the middle of a run. You get warning and a confirmation prompt if you use this outside secret mode (as for stopping in the middle of a run).
I …
> Small speed improvements for the event builder

- pax/config/XENON100.ini
- pax/config/XENON1T.ini
- pax/config/_base.ini
- pax/plugins/interaction_processing/BuildInteractions.py
- pax/plugins/peak_processing/PeakAreaCorrections.py
This ensures that the S1 and S2 correction values computed by Sander's saturation correction algorithm (see https://github.com/XENON1T/pax/pull/237) are saved even if we do not include them in the total correction (interaction.s2_area_correction and interaction.s1_area_correction).
We do not currently include the saturation correction for XENON1T since they're a bit more experimental than the other corrections (although they work fine for XENON100, they rely on the Monte Carlo LCE per-PMT map). Hopefully after we see they work well on a couple of datasets we can include them in the total correction, as we do for XENON100. You will always be able to access all individual corrections separately (see https://github.com/XENON1T/pax/pull/322).
> Compute saturation correction even if not included in total

- pax/config/XENON1T.ini
@adambrown1 found that S2 spatial correction has never been calculated in pax. In this update, we include the s2 correction in the processor task list.
> add S2 correction in task list

- pax/plugins/io/MongoDB.py
This addresses #607 by adding some random nonsense at the start of each acquisition monitor pickle file.  There will be a companion pull request in hax to make the acquisition monitor pulse reading code robust to this.
> Add random initial pickle to acquisition monitor file

- pax/config/SR1_parameters.ini
Forgot to update S2 xy correction map in ```SR1_parameters.ini``` to v2.2 (as in [hax.ini](https://github.com/XENON1T/hax/blob/v2.3.1/hax/hax.ini#L125) now). This config is mostly used in simulations now, but perhaps we should also use for hax [here](https://github.com/XENON1T/hax/blob/v2.3.1/hax/treemakers/posrec.py#L60) if not defined [there](https://github.com/XENON1T/hax/blob/v2.3.1/hax/hax.ini#L122) already, for example ```s2_patterns_file``` which has changed in ```XENON1T.ini``` since the ```pax_v6.8.0``` reprocessing, and we need to be consistent now for recalculations.
> Update S2 xy map in SR1 config

- .travis.yml
- requirements.txt
- setup.py
About half of our dependencies cannot have their versions changed without breaking pax.  After testing in my own fork, I've been able to identify which  can be upgrade and which cannot.  The ones that cannot will be marked as ignore with pyup.
> Split dependencies into upgradable and not upgradable

- pax/config/XENON1T.ini
- pax/config/_base.ini
- pax/plugins/peak_processing/ClassifyPeaks.py
- pax/plugins/signal_processing/BuildPeaks.py
This PR lowers the tight coincidence coincidence to two-fold in order to improve the acceptance of low-E events, as requested by @mcfatelin 
I also included a S1width (range_90p_area) in the classification, which should replace the [S1Width cut in LAX](https://github.com/XENON1T/lax/blob/master/lax/lichens/sciencerun0.py#L577).
> lowering tight coincidence to 2-fold

- pax/dsputils.py
- pax/plugins/ZLE.py
#712 included the addition of additional [smoothing and splitting](https://github.com/XENON1T/pax/pull/712/files#diff-5d2794434093c23639c8c8f1e5044cb2R203) when `find_intervals_above_threshold()` is called in the hitfinder. This added some numpy functions, which necessitated the removal of the numba speed boosting. This function is also caused during the ZLE phase of [fax](https://github.com/XENON1T/pax/blob/master/pax/plugins/ZLE.py#L55), which has since slowed down significantly. Unfortunately, since the numba boosting couldn't work on the current function, I didn't see a fix besides duplicating a good amount of code 🤷‍♂️ . In this PR, the old version of the function is instead called in `ZLE.py`, restoring fax's speed.
> Segregate hit smoothing
